### ISSUE TITLE
Sync videos betwee multiple RPi's

### ISSUE THREAD

**Issue by KenT2** [KenT2/pipresents-beep#12]
I came accross follwing link to sync the videos on multiple rpis,
it works well for me on 9 nos of rpi without any problem
if I want to integarte that in pi presents can you tell me how to do it.
https://github.com/turingmachine/omxplayer-sync

Transferred from gapless  https://github.com/KenT2/pipresents-gapless/issues/117

**Comment by ninadk1092** [comment]
@KenT2 any estimate when this issue will be fixed and released?

**Comment by KenT2** [comment]
maybe this winter

**Comment by RogierQ** [comment]
o nice! is it working on gapless?
as winter is almost gone ;)

**Comment by KenT2** [comment]
Ha Ha, winter is far from over, no snow yet.
It will never be in Gapless, only in Beep.
Got somewhat diverted because the Foundation announced there would be no further development on omxplayer and we should use VLC. Tried VLC but its some way from being an embedded videoplayer. Now I'm trying to sort out rotation of touchscrreens
Its going to be quite a project to do it so don't hold your breath, it may not even be possible.

**Comment by KenT2** [comment]
omxplayer is now deprecated and VLC has replaced omxplayer in Pi Presents. Not sure VLC can sync videos between multiple Pi's

**Comment by pramodmadhav** [comment]
can one set position in VLC (hr:min:sec:frames)

**Comment by KenT2** [comment]
You can in VLC but not in Pi Presents.
