### ISSUE TITLE
Automatic Slideshow of Pictures + Videos When USB Inserted

### ISSUE THREAD

**Issue by BzowK** [KenT2/pipresents-beep#13]
Good Afternoon - 

I'm trying to get Pi Presents to do something specific and so far have not been able to accomplish it, so wanted to post to see if it was possible and if so; hopefully get some direction.

_Apologies if this isn't the best place to post this, but is the only one I could find :)_

**Project Goal**
_This project is for non-tech savvy grandparents without internet to easily view pictures & videos of grandchildren on their TV._  

**Desired Configuration**
Configure Pi Presents on a RasPi which will do the following:
- At idle, stay at a static idle screen / background
- USB stick(s) will contains a mix of media files
- Once USB is inserted, start a slideshow of all media content (pictures & videos) which loops until stick is removed.  
- Images would be displayed for 5 seconds and if/when a video is encountered, it would simply play start -> end OR they could use a keyboard (via FLIRC) to change to the next / previous media
- Removing USB stick goes back to idle screen
_I considered converting everything to a video slideshow, but trying to make it easy for multiple family members to copy media to a flash drive & mail it to them to view._ 

As mentioned, I've so far been unable to make the above work.  If you have any suggestions, please let me know.  Thank You!

**Comment by KenT2** [comment]
Use a liveshow and its empty track facility which will play a specified track when the liveshow list obtained from the usb stick is empty, or usb stick removed.
The example pp_liveshowempty_1p4 shows how.
It may be necessary to shut down pi presents before removing the usb stick, try it a few times and see, you coulld add a button to the gpio to do this
There is an i/o plugin for a wireless remote, I have not done an IR one
