### ISSUE TITLE
playing video in layers

### ISSUE THREAD

**Issue by RogierQ** [KenT2/pipresents-beep#15]
is it possible to play a video over a playing video?
if i do now i gives a strange effect 2 videos fighting to be on top of the screen
i found the openexclusive function that does most of it but i wish that the screen does not go black on starting the video

**Comment by KenT2** [comment]
1. Use the --layer  omxplayer option in the video track. See omxplayer github for details

2. Cannot do much about the black screen. Its the time it takes the video to load. A more recent model of Pi will reduce it.
