### ISSUE TITLE
Audio not sync with video

### ISSUE THREAD

**Issue by RogierQ** [KenT2/pipresents-beep#16]
Hi!
On pi4 with buster my audio from a mp4 is not in sync.
In my config.txt i have gpu_mem=512
Is there more to do to get it in sync?
Thanks!

**Comment by KenT2** [comment]
No nothing you can do. Try playing the video using omxplayer from the command line. Instructions in omxplayer github. PP does no more than this.
Have a look at the issues on github, it might be something to do with the production of the video.

**Comment by lalo-uy** [comment]
I don't know omxplayer, but mplayer have options for specifying an offset for audio.
If that also exist you can add that option in Track Video Player
Options

**Comment by KenT2** [comment]
omxplayer does not have options for audio offset
