### ISSUE TITLE
"Display has no canvas" error

### ISSUE THREAD

**Issue by zvrso** [KenT2/pipresents-beep#18]
Hi Ken, I'm trying to set up an RPi 3B with RPi 7" touch (DSI0) and an external HDMI connected. The idea is to use the 7" touch for selection, and the HDMI for output. However I never get any output to the HDMI, I get "Profile Error: Display has no canvas HDMI0" no matter what I try - what am I missing? If I change Display to "DSI0" in profile the show will run on the 7" monitor.

I have tried the same setup with an RPi 4 with same result.

- clean install of latest Buster & updates
- followed Pi Presents install instructions

/roar

**Comment by KenT2** [comment]
On a 3b you can have only one display so if the DSI is connected the hdmi is not useable (except for videos using the video track special option)
On a Pi4 the two monitors should work. I have just tried the latest version of Buster with 2 hdmi displays and all is OK, can't easily check DSI0.
Have you got the monitor plugged into the correct hdmi port. Is the monitor plugged in before powering the Pi.
Do the two monitor form one big desktop in Raspbian and are seen in the screen configuration utiltiy?
If you continue to have problems please copy and paste the output on the terminal window which appears when PP is first started. You can do this is a terminal window by dragging and then right clicking.
BTW sound from audio tracks has been broken by the latest version of Buster. I will be isuing an updated version of PP in the next few days.
