### ISSUE TITLE
Audio Issues and help troubleshooting

### ISSUE THREAD

**Issue by Milky123123** [KenT2/pipresents-beep#19]
Hello Ken,

I would very much appreciate some advice if you have time.
I have previously installed beep on a pi3 with no issues and loved it.

I decided to build a new setup with a pi4 to take advantage of the dual display feature.
here is what my setup looks like:
-Rpi4 running Beep
-1x DSI screen (official 7" display)
-1x computer monitor connected to HDMI0
-I have a headphones connected to the A/V 3.5mm for audio 

My problem is that under certain situations I get audio garbel/distortion or sometime no audio at all.(I am trying to use local or A/V audio in all test instances)
-The problem is less noticeable when I only have one display connected.  but extreme when I have both displays connected.

The terminal window states " amixer: Cannot find the given element from control hw:0"
The terminal window states "uncollected garbage 100"
I sure this is relevant somehow.

Any suggestions on what I could to to remedy this issue?

Thanks,

Mike

**Comment by KenT2** [comment]
I think you might have hit one or both of two problems:

1. Pi Towers has recently changed the way audio devices are selected. To sort this you need to upgrade to the latest version of PP. Read the changelog and release notes for details.

This would account for  " amixer: Cannot find the given element from control hw:0"

Do not worry about the uncollected garbage. There always seems to be a little when PP exits. Worry only if it increases with time.

2. You have hit this bug:

https://github.com/raspberrypi/firmware/issues/1373

Just make sure you do not use HDMI audio device in any show/track.

Hope this helps

Ken
