### ISSUE TITLE
make the start of unclutter configurable

### ISSUE THREAD

**Issue by masseelch** [KenT2/pipresents-beep#35]
I wrote a wrapper around PiPresents to start / stop / control PiPresents to manage the execution of different profiles. 
To reliably kill PiPresents I am using *nix feature to kill a process (PiPresents) by its process group id. In that way I won't end up dangling / orphanged omxplayers all over my device. 

My displays do start unclutter as a service, since i never need the cursor and the displays sometimes do other stuff besides PiPresents. But since PiPresents does start unclutter, unclutter itself it is marked as child-process of PiPresents. So killing PiPresents in the way I do leads to unclutter being killed too. 

So i propose to add an option to toggle the start of unclutter when running PiPresents. 

I can draft a PR if you like.

**Comment by KenT2** [comment]
I will put an option in the next issue which could be a while. 

Meanwhile just comment out pp_displaymanager.py line 566 - os.system('unclutter > /dev/null 2>&1 &')

**Comment by KenT2** [comment]
sending SIGTERM to PP should shut it down successfullly. Hopefully with no dangling omxplayers. But I guess it will terminate unclutter even though it is started with an &

**Comment by masseelch** [comment]
Sending SIGTERM was what I did first. That sometimes is leaving omxplayer running in the background. If an error of some kind occurs and PiPresents shows a pop-up regarding that error SIGTERM will not work either. That is why I am doing it with pgids.

Commenting out the line works like a charm ☺️

**Comment by KenT2** [comment]
In 1.4.5e

**Comment by masseelch** [comment]
Great! I will update ASAP! Thank you very very much!!
