### ISSUE TITLE
Question: List Empty Track for Artliveshow

### ISSUE THREAD

**Issue by masseelch** [KenT2/pipresents-beep#39]
Me again, sorry to bother you so much lately :-)

There is an option to show a default track for a liveshow (List Empty Track). But this option does not seem to work on artliveshow. Is this just a bug or is this feature not implemented? If not, how can I be of help enabling this?

**Comment by KenT2** [comment]
The feature is not implemented. 

Do try the liveshow. The only difference is a short freeze at the end of each track which could be disguised by a suitable end to the video.

**Comment by masseelch** [comment]
You mean like fading to black at end / fading from black at start? The freeze would happen at the last black frame and it looks like a fade, yes?

**Comment by KenT2** [comment]
yes, or just a stationary scene at the end. Fade to black would disguise the very tiny gap where the background is shown

**Comment by masseelch** [comment]
Works like a charm. Thank you :-) 

BTW, do you have a Buy Me A Coffee Link or sth?
