### ISSUE TITLE
liveshow - sync mode fails on startup

### ISSUE THREAD

**Issue by masseelch** [KenT2/pipresents-beep#41]
If I have a liveshow with the sync-feature enabled with `.lock` file PP does not update its media-folder on startup. It simply removes the `.lock` file, but the files to move are not moved.

**Comment by KenT2** [comment]
Fixed. Try this new livelistfetcher
[pp_livelistfetcher.py.txt](https://github.com/KenT2/pipresents-beep/files/6564973/pp_livelistfetcher.py.txt)

**Comment by masseelch** [comment]
Worked. Thank you!
