### ISSUE TITLE
Moving from RP 3 to RP 4 and videos are not playing anymore

### ISSUE THREAD

**Issue by sky-love** [KenT2/pipresents-beep#42]
I tried to move my show that consists mainly of 10 min looped videos from RP 3b+ to RP 4 for performance reasons. Now when I try to play my show on RP4 nothing happens and the Terminal is returning this message from pipresents.py: "unpause for show False". Everything works beautifully with my setup on RP3 including switching to OMXPlayer due to VLC hanging a lot but can't start my videos on RP 4. I even reinstalled everything from scratch rather than using my flashed RP 3 card and still can't even play the video from the sample shows on my RP4. Any idea? Thank you!

**Comment by KenT2** [comment]
"unpause for show False" is a debug statement  I left it in by mistake. Seeing this indicates that PP is running.
Have a look at the guidance for Pi4 displays in Section 10.1 of the Beep manual. My best guess is that the monitor is plugged into the wrong port.
