### ISSUE TITLE
VL6180X Support

### ISSUE THREAD

**Issue by W1ldKard** [KenT2/pipresents-beep#49]
Hi,
would there be support for VL6180X in the future?
I would like to adjust my screen brightness depending on ambient light and trigger Play/Pause using this sensor.

Also, would there be at least a fade transition added in the future? Cut transition is a bit jarring.

**Comment by KenT2** [comment]
The VL6180X appears to be for robotics. It has a range of only 10 cms and I don't think its going to be much use for Pi presents applications.

If you know a bit of Python it would not be difficult to modify one of the I/O device drivers in pp_io_plugins directory. The I/O driver API provides a framework to poll a device such as yours at intervals and generate an input event if the range moves across a threshold.

To change the brightness of your monitor I suspect the best way would be to include the interface with the monitor in the I/O device driver.
