### ISSUE TITLE
pp_openclose start with image

### ISSUE THREAD

**Issue by pelicanmedia** [KenT2/pipresents-beep#5]
Hi Ken,

Sorry, not really an issue, a query...

I am playing with the _pp_openclose_ profile and would like it to start with showing _image1.jpg_ then when a switch P1_18 is sent to ground _image2.jpg_ is shown. When P1_18 is released _image1.jpg_ is shown again (rather than the black screen).
I have attempted to make changes to the config files with no avail or with errors.
Would you be able to point me in the right direction?

Thanks.

**Comment by KenT2** [comment]
Two alternatives
a repeating mediashow. In track1 associate  the press of the button to the down command. I track 2 assign the release of the button to the down command.
a radiobutton show. In the show associate the the press of the button with 'play track1' and the release with 'play track2'
