### ISSUE TITLE
loading screen between movies

### ISSUE THREAD

**Issue by AlainCx** [KenT2/pipresents-beep#53]
Hello,
with a new project I have to set up a waiting screen between each video played. In reality it's a video with a countdown displayed.
There's a first top menu where the user have to choose between 4 videos.
During the waiting screen, the user can go back to home menu with a button. If not the next movie is played.
A touchscreen allows to control the device.

If he/she choses :

- the 1st movie, the following movies are played : 
Movie 1 > Waiting screen A > Movie 2 > Waiting screen B > Movie 3 > Waiting screen C > Movie 4 > return to home menu

- the 2nd movie, the following movies are played : 
Movie 2 > Waiting screen B > Movie 3 > Waiting screen C > Movie 4 > return to home menu

- the 3rd movie, the following movies are played : 
Movie 3 > Waiting screen C > Movie 4 > return to home menu

- the 4th movie, the following movies are played : 
Movie 4 > return to home menu

I tried several things witout success. I played with subshows and "show control at end" field but unsuccessfool.

Any advice ?

Thanks,
Alain

**Comment by KenT2** [comment]
My solution would be a menushow with 4 mediashows. Each mediashow would be single run so at the end it returns to the menushow.
The control command in the waiting tracks  to return to the menu needs to be exit rather than stop. Stop just moves to the next track whereas exit stops the track and then the show hens returniing to the menushow.

**Comment by AlainCx** [comment]
Thanks, I'll give a try right away !

**Comment by AlainCx** [comment]
I used 4 mediashows inside a radiobuttonshow and it works without problem.

Thanks !
